name: inst_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  firebase_core: ^3.0.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.0.0

  flutter_bloc: ^7.2.0
  provider: ^6.0.5
  get_it: ^7.2.0

  http: ^1.2.2
  dio: ^4.0.6

  google_sign_in: ^6.2.0

  flutter_secure_storage: ^9.2.4
  lottie: ^2.3.0
  blurhash_ffi: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/animation/
